# Generated by Django 4.2.3 on 2023-07-09 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('categaory', models.CharField(choices=[('Air Max', 'Air Max'), ('Air Force', 'Air Force'), ('Air Vapormax', 'Air Vapormax'), ('Air Jordan', 'Air Jordan'), ('Kyrie', 'Kyrie'), ('Lebron', 'Lebron')], default='Catagory', max_length=200)),
                ('season', models.CharField(choices=[('Summer', 'Summer'), ('Spring', 'Spring'), ('Autumn', 'Autumn')], default='season', max_length=200)),
                ('color', models.CharField(choices=[('White', 'White'), ('Yellow', 'Yellow'), ('Red', 'Red'), ('Green', 'Green'), ('Violet', 'Violet'), ('Dark', 'Dark'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Pink', 'Pink')], default='color', max_length=200)),
                ('size', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField(blank=True, null=True)),
                ('main_image_url', models.URLField(max_length=2000)),
                ('front_image', models.CharField(max_length=2000)),
                ('back_image', models.CharField(max_length=2000)),
                ('side_image', models.CharField(max_length=2000)),
                ('shoe_available', models.BooleanField()),
                ('is_delete', models.BooleanField()),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(default=False, max_length=2083)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoe.shoes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
